# Site settings
title: Practice makes perfect
email: shinapp7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Paypulse CEO Bitch.
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "http://paypulse.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  paypulse
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: rmsubekti
facebook:
  app_id: 1234567
  publisher: 1234567

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/WPF/:title'}}

defaults1:
    - {scope: {type: posts}, values: {layout: post, permalink: '/C#/:title'}}
include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock


paginate: 12
paginate_path: '/WPF/:num'
